# Generated by Django 3.2.2 on 2021-05-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='likes',
            new_name='liker',
        ),
    ]
